# Generated by Django 4.2.7 on 2024-02-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=255)),
                ('authorName', models.CharField(max_length=255)),
                ('bookDescription', models.CharField(max_length=255)),
            ],
        ),
    ]
